output_limit: use add_library instead of px4_add_library
px4_add_library adds uorb dependencies, which since 022208b6aab [formerly cf26f24387d] added libm.
This in turn led to build failures for px4_io-v2 in the form of:
__aeabi_f2d' wf_sqrt.c:(.text.sqrtf+0x54): undefined reference to
__aeabi_ddiv'


Former-commit-id: d0fd60de8d506500f810848e22628581251655d0